name: misi_paket
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_map: ^6.1.0
  flutter_typeahead: ^4.4.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  http: 1.4.0
  latlong2: ^0.9.0
  shared_preferences: ^2.2.2
  web_socket_channel: 3.0.3
  local_auth: ^2.1.6
  lottie: ^3.0.0
  centrifuge: ^0.16.0





flutter_launcher_icons:
  android: true
  ios: false
  image_path: "lib/assets/iconapk.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Logo.png
    - lib/assets/icons/motor_kurir.png
    - lib/assets/food.png
    - lib/assets/goods.png
    - lib/assets/passanger.png
    - lib/assets/promo1.png
    - lib/assets/promo2.jpg
    - lib/assets/iconapk.png
    - lib/assets/hi_icon.png
    - lib/assets/sembako.png
    - "lib/assets/Fainyetir.json"
